Repository Ameciclo/botaprarodar, pull requests merged in 2021-12, with the labels that each got.

#123 feature: not allow select a user when he is blocked on withdraw bike
  app/src/main/java/app/igormatos/botaprarodar/presentation/adapter/SelectUserViewHolder.kt
Labels: enhancement, hotfix

#122 Feature/remove useless classes
  app/build.gradle
  app/src/main/java/app/igormatos/botaprarodar/data/model/UserRequest.kt
  app/src/main/java/app/igormatos/botaprarodar/di/Modules.kt
  app/src/main/java/app/igormatos/botaprarodar/domain/converter/user/UserRequestConvert.kt
  app/src/main/java/app/igormatos/botaprarodar/domain/usecase/userForm/UserFormUseCase.kt
  app/src/main/java/app/igormatos/botaprarodar/presentation/adapter/ItemAdapter.kt
  app/src/main/java/app/igormatos/botaprarodar/presentation/authentication/AuthenticationActivity.kt
  app/src/main/java/app/igormatos/botaprarodar/presentation/authentication/EmailValidationFragment.kt
  app/src/main/java/app/igormatos/botaprarodar/presentation/authentication/PasswordRecoveryFragment.kt
  app/src/main/java/app/igormatos/botaprarodar/presentation/authentication/RegistrationFragment.kt
  app/src/main/java/app/igormatos/botaprarodar/presentation/authentication/SignInFragment.kt
  app/src/main/java/app/igormatos/botaprarodar/presentation/authentication/viewmodel/RegistrationState.kt
  app/src/main/java/app/igormatos/botaprarodar/presentation/authentication/viewmodel/RegistrationViewModel.kt
  app/src/main/java/app/igormatos/botaprarodar/presentation/bikewithdraw/choosebicycle/WithdrawActivity.kt
  app/src/main/java/app/igormatos/botaprarodar/presentation/bikewithdraw/chooseuser/ChooseUserActivity.kt
  app/src/main/java/app/igormatos/botaprarodar/presentation/fullscreenimage/FullscreenImageActivity.kt
  app/src/main/java/app/igormatos/botaprarodar/presentation/returnbicycle/ReturnOldBikeActivity.kt
  app/src/main/java/app/igormatos/botaprarodar/presentation/returnbicycle/RideQuizActivity.kt
  app/src/main/java/app/igormatos/botaprarodar/presentation/welcome/WelcomeActivity.kt
  app/src/main/res/layout/activity_authentication.xml
  app/src/main/res/layout/activity_choose_user.xml
  app/src/main/res/layout/activity_fullscreen_image.xml
  app/src/main/res/layout/activity_rent.xml
  app/src/main/res/layout/activity_return_old_bike.xml
  app/src/main/res/layout/activity_welcome.xml
  app/src/main/res/layout/fragment_email_validation.xml
  app/src/main/res/layout/fragment_password_recovery.xml
  app/src/main/res/layout/fragment_registration.xml
  app/src/main/res/layout/fragment_sign_in.xml
  app/src/main/res/navigation/authentication_nav_graph.xml
  app/src/test/java/app/igormatos/botaprarodar/domain/usecase/userForm/UserFormUseCaseTest.kt
  app/src/test/java/app/igormatos/botaprarodar/presentation/authentication/RegistrationViewModelTest.kt
  app/src/test/java/app/igormatos/botaprarodar/utils/UserFixtures.kt
  core/src/main/java/app/igormatos/botaprarodar/core/MyClass.kt
  settings.gradle
Labels: enhancement

#124 changed to variable age for birthday
  app/src/androidTest/java/app/igormatos/botaprarodar/Fixtures.kt
  app/src/main/java/app/igormatos/botaprarodar/domain/model/User.kt
  app/src/main/java/app/igormatos/botaprarodar/presentation/user/userform/UserFormFragment.kt
  app/src/main/java/app/igormatos/botaprarodar/presentation/user/userform/UserFormViewModel.kt
  app/src/main/res/layout/fragment_user_form.xml
  app/src/main/res/values/strings.xml
  app/src/test/java/app/igormatos/botaprarodar/presentation/user/userform/UserFormViewModelTest.kt
  app/src/test/java/app/igormatos/botaprarodar/utils/UserFixtures.kt
Labels: wontfix

#125 Feature: Adding filter when selecting an user
  app/src/main/java/app/igormatos/botaprarodar/presentation/bikewithdraw/SelectUserFragment.kt
  app/src/main/java/app/igormatos/botaprarodar/presentation/bikewithdraw/viewmodel/SelectUserViewModel.kt
  app/src/main/res/layout/fragment_select_user.xml
Labels: enhancement

#127 Fix: Fix bug EditText "User Adress" and checked nullable text (User N…
  app/src/main/java/app/igormatos/botaprarodar/common/biding/CustomEditTextBindingAdapter.kt
  app/src/main/java/app/igormatos/botaprarodar/common/biding/TextBindingUserAdapter.kt
  app/src/main/java/app/igormatos/botaprarodar/common/biding/utils/ViewValidationUtil.kt
  app/src/main/java/app/igormatos/botaprarodar/common/components/CustomEditText.kt
  app/src/main/java/app/igormatos/botaprarodar/common/extensions/EditTextExtension.kt
  app/src/main/res/layout/fragment_user_form.xml
Labels: hotfix

#130 Fix: Adjusted BikeWithdraw and ReturnBike navigation flux
  app/src/main/java/app/igormatos/botaprarodar/presentation/bikewithdraw/BikeWithdrawActivity.kt
  app/src/main/java/app/igormatos/botaprarodar/presentation/returnbicycle/ReturnBikeActivity.kt
  build.gradle
  toolkit/build.gradle
Labels: hotfix
