Repository Ameciclo/botaprarodar, pull requests merged in 2022-02, with the labels that each got.

#136 update: updated the app to new logo, and refactored modules files
  app/src/main/ic_launcher-playstore.png
  app/src/main/java/app/igormatos/botaprarodar/common/BprApplication.kt
  app/src/main/java/app/igormatos/botaprarodar/di/FirebaseModules.kt
  app/src/main/java/app/igormatos/botaprarodar/di/Modules.kt
  app/src/main/java/app/igormatos/botaprarodar/di/RespositoryModules.kt
  app/src/main/java/app/igormatos/botaprarodar/di/UseCaseModules.kt
  app/src/main/java/app/igormatos/botaprarodar/di/ViewModelModules.kt
  app/src/main/res/drawable/ic_launcher_background.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  app/src/main/res/mipmap-hdpi/ic_launcher.png
  app/src/main/res/mipmap-hdpi/ic_launcher_foreground.png
  app/src/main/res/mipmap-hdpi/ic_launcher_round.png
  app/src/main/res/mipmap-mdpi/ic_launcher.png
  app/src/main/res/mipmap-mdpi/ic_launcher_foreground.png
  app/src/main/res/mipmap-mdpi/ic_launcher_round.png
  app/src/main/res/mipmap-xhdpi/ic_launcher.png
  app/src/main/res/mipmap-xhdpi/ic_launcher_foreground.png
  app/src/main/res/mipmap-xhdpi/ic_launcher_round.png
  app/src/main/res/mipmap-xxhdpi/ic_launcher.png
  app/src/main/res/mipmap-xxhdpi/ic_launcher_foreground.png
  app/src/main/res/mipmap-xxhdpi/ic_launcher_round.png
  app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_foreground.png
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.png
  app/src/main/res/values/ic_launcher_background.xml
Labels: enhancement

#138 fix: resolved dark theme bug that was removing text and icon colors, …
  app/src/main/java/app/igormatos/botaprarodar/presentation/components/FinishActionComponent.kt
  app/src/main/java/app/igormatos/botaprarodar/presentation/components/WithdrawConfirmation.kt
  app/src/main/java/app/igormatos/botaprarodar/presentation/components/WithdrawStepperComponent.kt
Labels: bug, wontfix

#139 Development
  app/src/main/java/app/igormatos/botaprarodar/presentation/components/FinishActionComponent.kt
  app/src/main/java/app/igormatos/botaprarodar/presentation/components/WithdrawConfirmation.kt
  app/src/main/java/app/igormatos/botaprarodar/presentation/components/WithdrawStepperComponent.kt
Labels: bugfix
